USE [master]
GO
/****** Object:  Database [Musician]    Script Date: 12/30/2025 7:42:25 PM ******/
CREATE DATABASE [Musician]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Musician', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Musician.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Musician_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Musician_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Musician] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Musician].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Musician] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Musician] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Musician] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Musician] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Musician] SET ARITHABORT OFF 
GO
ALTER DATABASE [Musician] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Musician] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Musician] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Musician] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Musician] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Musician] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Musician] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Musician] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Musician] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Musician] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Musician] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Musician] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Musician] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Musician] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Musician] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Musician] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Musician] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Musician] SET RECOVERY FULL 
GO
ALTER DATABASE [Musician] SET  MULTI_USER 
GO
ALTER DATABASE [Musician] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Musician] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Musician] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Musician] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Musician] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Musician] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Musician', N'ON'
GO
ALTER DATABASE [Musician] SET QUERY_STORE = ON
GO
ALTER DATABASE [Musician] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Musician]
GO
/****** Object:  Table [dbo].[Album]    Script Date: 12/30/2025 7:42:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Album](
	[Id] [int] NOT NULL,
	[Title] [varchar](50) NOT NULL,
	[Date] [date] NULL,
	[MusicianId] [int] NULL,
 CONSTRAINT [PK_Album] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AlbumSong]    Script Date: 12/30/2025 7:42:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AlbumSong](
	[AlbumId] [int] NULL,
	[SongTitle] [varchar](50) NOT NULL,
 CONSTRAINT [PK_AlbumSong] PRIMARY KEY CLUSTERED 
(
	[SongTitle] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Instrument]    Script Date: 12/30/2025 7:42:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Instrument](
	[Name] [varchar](50) NOT NULL,
	[Key] [varchar](50) NULL,
 CONSTRAINT [PK_Instrument] PRIMARY KEY CLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Musician]    Script Date: 12/30/2025 7:42:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Musician](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[PhNumber] [varchar](50) NULL,
	[City] [varchar](50) NULL,
	[Street] [varchar](50) NULL,
 CONSTRAINT [PK_Musician] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MusicianInstrument]    Script Date: 12/30/2025 7:42:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MusicianInstrument](
	[MusicianId] [int] NOT NULL,
	[InstrumentName] [varchar](50) NOT NULL,
 CONSTRAINT [PK_MusicianInstrument] PRIMARY KEY CLUSTERED 
(
	[MusicianId] ASC,
	[InstrumentName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MusicianSong]    Script Date: 12/30/2025 7:42:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MusicianSong](
	[MusicianId] [int] NOT NULL,
	[SongTitle] [varchar](50) NOT NULL,
 CONSTRAINT [PK_MusicianSong] PRIMARY KEY CLUSTERED 
(
	[MusicianId] ASC,
	[SongTitle] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Song]    Script Date: 12/30/2025 7:42:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Song](
	[Title] [varchar](50) NOT NULL,
	[Auther] [varchar](50) NULL,
 CONSTRAINT [PK_Song] PRIMARY KEY CLUSTERED 
(
	[Title] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Album]  WITH CHECK ADD  CONSTRAINT [FK_Album_Musician] FOREIGN KEY([Id])
REFERENCES [dbo].[Musician] ([Id])
GO
ALTER TABLE [dbo].[Album] CHECK CONSTRAINT [FK_Album_Musician]
GO
ALTER TABLE [dbo].[AlbumSong]  WITH CHECK ADD  CONSTRAINT [FK_AlbumSong_Album] FOREIGN KEY([AlbumId])
REFERENCES [dbo].[Album] ([Id])
GO
ALTER TABLE [dbo].[AlbumSong] CHECK CONSTRAINT [FK_AlbumSong_Album]
GO
ALTER TABLE [dbo].[MusicianInstrument]  WITH CHECK ADD  CONSTRAINT [FK_MusicianInstrument_Instrument] FOREIGN KEY([InstrumentName])
REFERENCES [dbo].[Instrument] ([Name])
GO
ALTER TABLE [dbo].[MusicianInstrument] CHECK CONSTRAINT [FK_MusicianInstrument_Instrument]
GO
ALTER TABLE [dbo].[MusicianInstrument]  WITH CHECK ADD  CONSTRAINT [FK_MusicianInstrument_Musician] FOREIGN KEY([MusicianId])
REFERENCES [dbo].[Musician] ([Id])
GO
ALTER TABLE [dbo].[MusicianInstrument] CHECK CONSTRAINT [FK_MusicianInstrument_Musician]
GO
ALTER TABLE [dbo].[MusicianSong]  WITH CHECK ADD  CONSTRAINT [FK_MusicianSong_Musician] FOREIGN KEY([MusicianId])
REFERENCES [dbo].[Musician] ([Id])
GO
ALTER TABLE [dbo].[MusicianSong] CHECK CONSTRAINT [FK_MusicianSong_Musician]
GO
ALTER TABLE [dbo].[MusicianSong]  WITH CHECK ADD  CONSTRAINT [FK_MusicianSong_Song] FOREIGN KEY([SongTitle])
REFERENCES [dbo].[Song] ([Title])
GO
ALTER TABLE [dbo].[MusicianSong] CHECK CONSTRAINT [FK_MusicianSong_Song]
GO
ALTER TABLE [dbo].[Song]  WITH CHECK ADD  CONSTRAINT [FK_Song_AlbumSong] FOREIGN KEY([Title])
REFERENCES [dbo].[AlbumSong] ([SongTitle])
GO
ALTER TABLE [dbo].[Song] CHECK CONSTRAINT [FK_Song_AlbumSong]
GO
USE [master]
GO
ALTER DATABASE [Musician] SET  READ_WRITE 
GO
